### PR TITLE
Fix pointers to value types (like *string)

### PR DESCRIPTION
**Pull request by jamesbibby**
When using a struct with *string elements makename() was returning .string, which was translated into ref "#/definitions/.string" which was not an available model reference and would throw errors in the swagger UI

To fix this when t.PkgPath() returns "" the name is used alone without the path. (this happens for built in types only) . This prevents filepath.Base(t.PkgPath()) from returning "."

### CODE REVIEW

**Comment by jamesbibby** [comment]
Any chance of merging this fix?

**Comment by jamesbibby** [comment]
@savaki Is there anything else I can provide to show you the fix for this in action?   A reproduction case?    We are going to use my fork for now but I would rather contribute the fix back into your project.

**Comment by coli** [comment]
I'll need this fix too

**Comment by savaki** [comment]
Sorry for the slowness here.  Was buried with other projects.  If you can add some test cases, we're good to go if you're still interested in merging this.

**Comment by jamesbibby** [comment]
In writing the test I found a better solution.   My previous fix was really just masking the problem.   For pointer types I changed inspect to simply recurse with the t.Elem() type and the same json tag.   This resolves types appropriately for both struct pointers and primitive pointers correctly.   I have added a test and a StringPtr value in the Pet spec.

**Comment by jamesbibby** [comment]
If you want to see the tests fail in this new test case, simply revert the change on line 60 of swagger/reflect.go and keep the tests and test data the same

**Comment by jamesbibby** [comment]
bump @savaki

**Comment by jamesbibby** [comment]
Hey @savaki I would love to get back on the main repo for this, any chance you can merge now.   I re-implemented in a slightly cleaner way and added tests

**Comment by jamesbibby** [comment]
@savaki bump

**Comment by jamesbibby** [comment]
Hey @savaki is there anything else you need me to do here?

**Comment by miketonks** [comment]
+1

**Pull request closed without merging**
